### ISSUE TITLE
The filenames inside the releases are wrong

### ISSUE THREAD

**Issue by olivertzeng** [Friends-of-Monika/mas-noises#1]
the filenames aren't supposed to be like the following ig, it's supposed to be a directory name instead

❯ cd noises-submod-1.1.2-1/
❯ l
 game\Submods\
 'game\Submods\Noises Submod\button.rpy'
 'game\Submods\Noises Submod\header.rpy'
 'game\Submods\Noises Submod\noises.rpy'
 'game\Submods\Noises Submod\res\'
 'game\Submods\Noises Submod\res\audio\birds.ogg'
 'game\Submods\Noises Submod\res\audio\brown.ogg'
 'game\Submods\Noises Submod\res\audio\chatter.ogg'
 'game\Submods\Noises Submod\res\audio\chickens.ogg'
 'game\Submods\Noises Submod\res\audio\cicadas.ogg'
 'game\Submods\Noises Submod\res\audio\city.ogg'
 'game\Submods\Noises Submod\res\audio\clock.ogg'
 'game\Submods\Noises Submod\res\audio\coffeeshop.ogg'
 'game\Submods\Noises Submod\res\audio\crickets.ogg'
 'game\Submods\Noises Submod\res\audio\fan.ogg'
 'game\Submods\Noises Submod\res\audio\fire.ogg'
 'game\Submods\Noises Submod\res\audio\forest.ogg'
 'game\Submods\Noises Submod\res\audio\frogs.ogg'
 'game\Submods\Noises Submod\res\audio\heartbeat.ogg'
 'game\Submods\Noises Submod\res\audio\highway.ogg'
 'game\Submods\Noises Submod\res\audio\machinery.ogg'
 'game\Submods\Noises Submod\res\audio\office.ogg'
 'game\Submods\Noises Submod\res\audio\owls.ogg'
 'game\Submods\Noises Submod\res\audio\pink.ogg'
 'game\Submods\Noises Submod\res\audio\purring.ogg'
 'game\Submods\Noises Submod\res\audio\rain.ogg'
 'game\Submods\Noises Submod\res\audio\rainroof.ogg'
 'game\Submods\Noises Submod\res\audio\river.ogg'
 'game\Submods\Noises Submod\res\audio\seagulls.ogg'
 'game\Submods\Noises Submod\res\audio\shower.ogg'
 'game\Submods\Noises Submod\res\audio\snowstorm.ogg'
 'game\Submods\Noises Submod\res\audio\space.ogg'
 'game\Submods\Noises Submod\res\audio\thunder.ogg'
 'game\Submods\Noises Submod\res\audio\train.ogg'
 'game\Submods\Noises Submod\res\audio\typing.ogg'
 'game\Submods\Noises Submod\res\audio\uterus.ogg'
 'game\Submods\Noises Submod\res\audio\waterdrops.ogg'
 'game\Submods\Noises Submod\res\audio\waterfall.ogg'
 'game\Submods\Noises Submod\res\audio\waves.ogg'
 'game\Submods\Noises Submod\res\audio\whales.ogg'
 'game\Submods\Noises Submod\res\audio\white.ogg'
 'game\Submods\Noises Submod\res\audio\wind.ogg'
 'game\Submods\Noises Submod\res\audio\windchime.ogg'
 'game\Submods\Noises Submod\res\audio\windtrees.ogg'

**Comment by dreamscached** [comment]
I don't understand what exactly you think is wrong here.

**Comment by olivertzeng** [comment]
https://file.garden/Z3KB9Nblz3hn1Ntv/noises-submod-1.1.2-1.zip

**Comment by olivertzeng** [comment]
> I don't understand what exactly you think is wrong here.

you can compare this zip file with the file from the releases tab

**Comment by dreamscached** [comment]
Why would you download the submod .zip from somewhere that isn't the *actual* releases page?

**Comment by dreamscached** [comment]
Ah, I see now. I'll get that fixed.

**Comment by olivertzeng** [comment]
> Why would you download the submod .zip from somewhere that isn't the _actual_ releases page?

That isn't what i meant. The link i gave you is the zip that fixes the problem
while the original's contents looks like this
![圖片](https://github.com/user-attachments/assets/55c5ea88-1380-45e3-9049-d4545850e71f)

which means that the filename isn't for example `birds.ogg` but it's `game\Submods\Noises Submod\res\audio\birds.ogg` instead
keep in mind that it's a problem if you inspect the \ because linux uses / instead of \

**Comment by olivertzeng** [comment]
alr thanks

**Comment by dreamscached** [comment]
Yeah I know Linux uses `/`, must be an issue with the packaging script.

**Comment by dreamscached** [comment]
I updated the release, thank you for your report.

**Comment by olivertzeng** [comment]
> I updated the release, thank you for your report.

nice
